language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
apt_packages: libnetcdf-dev
env:
  global:
  - secure: sqrtxp9efTETl0I+q/tdZ9SdmC8AUUMABwKHoTfawmRAcKiUgO97ketmzMLD49M1ExIOXNx87YmqfvD7o/avRJ28L5tr7lms0LxdQyLzZf/vtvQm1yC/85g65Cq1B3k8ULoPNE9+2R+o8HblKU/qrtLLnh9aEtw+NrCQLAMhRbgC7ClyXYcd01ZLO9bvUhrU79Rk06e5x8wzVN6rmBcr2/OpRhAzwY+OoIT/YxqglNk3zRwVOyPoVBpOV8UdMYEjhpjAfUw4jA+cH1sk+hzWWb2MNUOcMCfNkzj/Og8qr/tw3JTeRiOPJRkH4Cb8iVtQjmrEYTD767zlTFivtjPU937BufMAGVECMccILA8I2IHNRfQzMlM25KZvvUlN7vXFEjTvglEbsJoX1H+RNfurlHxvPW9g1I+6SnMPPVhunP1YrIBv4Qascx0cqLv87QcABqAVHDNCDGZWLO0Tqh0dP69pF8ZQ0RVnXaIy6Q3XiWlpj10I1tf52L92qzLoal97UE1vthFPZziIEkCRNwMEqUFow1j18IgE2+qBdLojGlPWLbbzBQhieuI4PsYpf9xXUrLucxtQNNkAH2oS2RWFnI1eQF0OuK2FWKq5nHhIsK9GePfGGOwRMFSD1o9zHcs6fuBtPlDtkDa75YqWmw2JOykt2QIRRfJgF0jo+7xF0l4=